---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Instacart

```{r}

devtools::install_github("p8105/p8105.datasets") 
library(p8105.datasets)
data("instacart")



instacart %>% 
  count(aisle) %>% 
  filter(n>10000) %>% 
  mutate(
    aisle=factor(aisle),
    aisle= fct_reorder(aisle,n)
  ) %>% 
  plot_ly(x= ~aisle, y=~n,
          alpha=.5,type="bar", mode="markers", color= ~aisle,
          colors="viridis") %>% 
  layout(barmode="overlay",
         title= "Instacart Orders by Aisle",
         xaxis= list (title="Aisle Type", tickangle=45),
         yaxis=list (title= "Number of Orders"),
         showlegend=FALSE
        )
  
```

Column {data-width=350}
-----------------------------------------------------------------------



### NY NOAA

```{r}
devtools::install_github("p8105/p8105.datasets") 
library(p8105.datasets)
data("ny_noaa")
 

ny_noaa_df=
 ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, c("year", "month", "day"), sep="-") %>%
  filter(snow %in% c(1:100)) %>%
  slice(1:1000)
 
 ny_noaa_df %>%        
  plot_ly(y = ~snow, x = ~year, type = "box",
          colors = "viridis") %>% 
   layout(barmode="overlay",
               title = "Snowfall Histogram Of Years 2004-2010",
               xaxis = list(title = "Year"),
               yaxis = list(title = "Snowfall (mm)"))
```

### NYC Restaurant Inspection

```{r}

library(p8105.datasets)
data("rest_inspec")

rest_inspec %>%
  janitor::clean_names() %>%
  slice(1:500)%>%
plot_ly(x= ~cuisine_description, y= ~score, type="scatter", color= ~cuisine_description,
          mode= "markers") %>% 
  layout(showlegend = FALSE,barmode="overlay",
               title = "Restaurant Scores by Cuisine",
               xaxis = list(title = "Type of Food Served", tickangle = 45),
               yaxis = list(title = "Score"))

          


```


